import { Source_Sans_3, Rubik_Bubbles } from "next/font/google";

import "./globals.css";

const sans = Source_Sans_3({ subsets: ["latin"], weight: ["200", "300"] });
const rubik = Rubik_Bubbles({ subsets: ["latin"], weight: ["400"] }); // next/font 공부용도

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sans.className}>{children}</body>
    </html>
  );
}
